// src/views/components/Sources.jsx
import React from "react";

import { Container, Typography, Grow, Card } from "@mui/material";

export default function Sources(props) {
  return (
    <Grow in={true} timeout={1000}>
      <Container maxWidth="md" style={{ padding: "10px 0" }}>
        <Typography
          component="h1"
          variant="h3"
          align="left"
          color="textPrimary"
          gutterBottom
          style={{ paddingLeft: "16px" }}
        >
          Sources
        </Typography>
        <Card
          elevation={3}
          style={{
            padding: "16px 16px 16px 16px",
            margin: "0px 20px 20px 20px",
          }}
        >
          {props.sources.map((source, index) => (
            <div align="left" key={index} style={{ padding: "0 16px 0  16px" }}>
              {source.title}
              {": "}
              <a
                style={{ color: "inherit" }}
                href={source.url}
                target="_blank"
                rel="noreferrer"
              >
                Link
              </a>
            </div>
          ))}
        </Card>
      </Container>
    </Grow>
  );
}

// docs/components/ui/Sources.vue
<script setup>
defineProps({
  sources: Array,
});
</script>

<template>
  <section class="sources-section">
    <ul class="sources-list">
      <li v-for="(source, index) in sources" :key="index" class="source-item">
        <a :href="source.url" target="_blank" rel="noopener noreferrer">
          {{ source.title }}
        </a>
        <div v-if="source.author" class="source-meta">
          <span v-if="source.author">{{ source.author }}</span>
        </div>
      </li>
    </ul>
  </section>
</template>

<style scoped>
.sources-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.source-item {
  margin-bottom: 1rem;
}

.source-item a {
  color: #14a02e;
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s ease;
}

.source-item a:hover {
  color: #14a02eb2;
  text-decoration: underline;
}

.source-meta {
  font-size: 0.9rem;
}
</style>
